# -*- coding: utf-8 -*-
import datetime

# Form implementation generated from reading ui file '.\UI\Export_Boletin_Por_Fechas_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate

from Controller import ControlModule


class Ui_Dialog(object):
    def __int__(self):
        pass

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(273, 179)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 140, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.dateEdit_Inicio = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_Inicio.setGeometry(QtCore.QRect(140, 30, 110, 22))
        self.dateEdit_Inicio.setObjectName("dateEdit")
        self.dateEdit_Final = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_Final.setGeometry(QtCore.QRect(140, 90, 110, 22))
        self.dateEdit_Final.setObjectName("dateEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 94, 101, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.on_accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        init_date = datetime.datetime.replace(datetime.datetime.today() ,month=1)
        self.dateEdit_Inicio.setDate(init_date)
        self.dateEdit_Final.setDate(datetime.date.today())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Fecha de inicio:"))
        self.label_2.setText(_translate("Dialog", "Fecha de término:"))

    def on_accept(self):
        folderpath = QtWidgets.QFileDialog.getSaveFileName(self, "Ingrese un nombre para su archivo", filter="*.xlsx")
        if folderpath:
            file_path = folderpath[0]
            fecha_1 = self.dateEdit_Inicio.date().toString(QtCore.Qt.DateFormat.ISODate).split("-")
            fecha_2 = self.dateEdit_Final.date().toString(QtCore.Qt.DateFormat.ISODate).split("-")
            fecha_1 = fecha_1[0] + fecha_1[1] + fecha_1[2]
            fecha_2 = fecha_2[0] + fecha_2[1] + fecha_2[2]
            ventas_con_retiros = ControlModule.Get_Ventas_por_Fechas(int(fecha_1), int(fecha_2))
            ControlModule.Write_excel(ventas_con_retiros, folderpath)

